### ISSUE TITLE
Crash when using ElevenLabs & Recasepunc/Vosk

### ISSUE THREAD

**Issue by GCPins** [lugia19/Echo-XI#2]
Traceback:

`File "C:\Users\gcpins\Documents\Speech2Speech\speechToSpeech.py", line 117, in <module>
    main()
  File "C:\Users\gcpins\Documents\Speech2Speech\speechToSpeech.py", line 37, in main
    srProvider.recognize_loop()
  File "C:\Users\gcpins\Documents\Speech2Speech\speechRecognition\VoskProvider.py", line 93, in recognize_loop
    process_text(recognizedText, self.chosenLanguage)
  File "C:\Users\gcpins\Documents\Speech2Speech\speechToSpeech.py", line 49, in process_text
    helper.ttsProvider.synthesizeAndPlayAudio(translatedText, helper.chosenOutput)
  File "C:\Users\gcpins\Documents\Speech2Speech\ttsProviders\ElevenlabsProvider.py", line 56, in synthesizeAndPlayAudio
    self.ttsVoice.generate_and_stream_audio(prompt, outputDeviceIndex,
AttributeError: 'ElevenLabsVoice' object has no attribute 'generate_and_stream_audio'`

Windows 11
Using Python 3.10.0

Crashes after transcribing speech (presumably when sending transcribed text to 11Labs API).

**Comment by lugia19** [comment]
There was an update pushed yesterday, have you downloaded that?
Also make sure you're on the latest version of elevenlabslib, you can do `pip install -r requirements.txt --upgrade`

My advice would be to start fresh and see if it still occurs.

**Comment by GCPins** [comment]
> There was an update pushed yesterday, have you downloaded that?
> Also make sure you're on the latest version of elevenlabslib, you can do `pip install -r requirements.txt --upgrade`
> 
> My advice would be to start fresh and see if it still occurs.

I did download the update (with git pull), and installed the requirements, but I have not run the pip install command with the --upgrade flag. I'll try that - thanks.

**Comment by lugia19** [comment]
Yeah, you'll want to make sure you're on the latest version of elevenlabslib, as the update from yesterday relies on an update to that library (that I also pushed yesterday).

**Comment by GCPins** [comment]
That fixed it - thanks.
